### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by mattiaverga** [ahp-electronics/libahp-xc#1]
Please add a license file to the repo

**Comment by mattiaverga** [comment]
SOrry, didn't notice the file is already present....

**Comment by mattiaverga** [comment]
I'm reopening again this issue, but for a different reason: while reviewing the package for inclusion in Fedora Linux, it was brought to my attention that, while the license file is GPL-3.0-or-later, the header in sources reports they are licensed as MIT...

So, what is the correct license, `GPL-3.0-or-later` or `MIT`? Or is the code dual licensed `GPL-3.0-or-later OR MIT`?

**Comment by iliaplatone** [comment]
@mattiaverga can you check if this issue was fixed please?
Thanks

**Comment by mattiaverga** [comment]
@iliaplatone it is not: `LICENSE.md` reports a GPL-3.0-or-later text license, while headers in code files refer to be licensed under MIT.
It is not clear at all what the correct license is.

**Comment by iliaplatone** [comment]
@mattiaverga Just updated rs232.c, can you tell me other files with a wrong heading please?
Thanks

**Comment by mattiaverga** [comment]
Indeed, rs232.c was the only one left with wrong headers and, of course, the only one I checked when you asked me previously... 😅
I think everything is fixed now. Thanks.
